# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.6 on 2017-04-07 15:33
=======
# Generated by Django 1.11 on 2017-04-07 15:36
>>>>>>> 7f99f99edca9f2b759b4ed903fa69a40cee1f671
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=200)),
                ('powers', models.SlugField(max_length=200)),
                ('occupation', models.TextField()),
                ('first_appearance', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('image', models.ImageField(blank=True, upload_to=b'personajes')),
=======
                ('image', models.ImageField(blank=True, upload_to='personajes')),
>>>>>>> 7f99f99edca9f2b759b4ed903fa69a40cee1f671
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('image', models.ImageField(blank=True, upload_to=b'universo')),
=======
                ('image', models.ImageField(blank=True, upload_to='universo')),
>>>>>>> 7f99f99edca9f2b759b4ed903fa69a40cee1f671
            ],
        ),
    ]
