# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=200)),
                ('powers', models.SlugField(max_length=200)),
                ('occupation', models.TextField()),
                ('first_appearance', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='personajes')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='universo')),
            ],
        ),
    ]
