# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='comic',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='comic',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='company',
            index_together=set([('id', 'slug')]),
        ),
    ]
